name: xleaflet
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xwidgets=0.13.1
  - xleaflet=0.3.1
  - xeus-cling=0.4.7
  - ipyleaflet=0.9.1
  - notebook >=5.4
  - widgetsnbextension >=3.0.0
