name: xleaflet
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor=0.19.0
  - xwidgets=0.15.0
  - xleaflet=0.5.0
  - xeus-cling=0.4.9
  - ipyleaflet>=0.9.1
  - notebook >=5.4
  - widgetsnbextension >=3.0.0
