name: xleaflet
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor>=0.18.1
  - xwidgets=0.14.0
  - xleaflet=0.4.0
  - xeus-cling=0.4.8
  - ipyleaflet>=0.9.1
  - notebook >=5.4
  - widgetsnbextension >=3.0.0
