name: xleaflet
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor=0.19.1
  - xwidgets=0.16.0
  - xleaflet=0.6.0
  - xeus-cling=0.4.10
  - ipyleaflet>=0.9.1
  - notebook >=5.4
  - widgetsnbextension >=3.0.0
