name: xleaflet
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xwidgets=0.12.0
  - xleaflet=0.2.0
  - xeus-cling=0.4.5
  - ipyleaflet=0.9.0
  - notebook >=5.4
  - widgetsnbextension >=3.0.0
