name: xleaflet
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus=1.0.0
  - cppzmq
  - xproperty=0.11.0
  - xwidgets=0.25.0
  - xtensor=0.23.0
  # Test dependencies
  - pybind11=2.4
  - pybind11_json=0.2.2
  - ipyleaflet=0.13.0

